name: Build Apps

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14.6"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Windows App
        if: runner.os == 'Windows'
        run: |
          pyinstaller --onefile --windowed --icon assets/app_icon.ico --name "Chess Tournament Maker PT" --collect-all customtkinter Chess-Tournament-Maker-PT.py

      - name: Build macOS App
        if: runner.os == 'macOS'
        run: |
          pyinstaller --windowed --name "Chess Tournament Maker PT" --collect-all customtkinter Chess-Tournament-Maker-PT.py

      - name: Upload Windows Artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: Chess-Tournament-Maker-PT
          path: dist/

      - name: Upload macOS Artifact
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: Chess-Tournament-Maker-PT
          path: dist/
